### ISSUE TITLE
【求助】安装错误

### ISSUE THREAD

**Issue by 1717tian** [noneplugin/nonebot-plugin-memes-api#5]
使用两个插件（api/非api版本）都报错   ImportError: cannot import name 'inherit_supported_adapters' from 'nonebot.plugin' 
重装nonebot无果  这次更新版本发生 之前版本0.5.1（nonebot-plugin-memes-0.5.1）正常

> `04-11 20:09:49 [ERROR] nonebot | Failed to import "nonebot_plugin_memes_api"                                            Traceback (most recent call last):                                                                                        File "C:\zhenxun_bot\bot.py", line 15, in <module>                                                                        nonebot.load_plugins("extensive_plugin")                                                                              File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins                                                                             return manager.load_all_plugins()                                                                                     File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins                                                                     return set(                                                                                                           File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>                                                                            filter(None, (self.load_plugin(name) for name in self.available_plugins))                                           > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin                                                                          module = importlib.import_module(                                                                                     File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module                                                                                                                       return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1050, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                                                      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked                                             File "<frozen importlib._bootstrap>", line 688, in _load_unlocked                                                       File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module                                                                          super().exec_module(module)                                                                                           File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                 File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                            File "C:\zhenxun_bot\extensive_plugin\nonebot_plugin_memes_api\__init__.py", line 15, in <module>                         from nonebot.plugin import PluginMetadata, inherit_supported_adapters                                               ImportError: cannot import name 'inherit_supported_adapters' from 'nonebot.plugin' (C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Kf6_FMLx-py3.10\lib\site-packages\nonebot\plugin\__init__.py)   `

**Comment by MeetWq** [comment]
升级nonebot

**Comment by 1717tian** [comment]
> 升级nonebot

已重置 2.1.3 2.2.0 报错均如上 
可能是在这目录下迭代升级太多了 尝试换个目录新开poetry

**Comment by MeetWq** [comment]
> > 升级nonebot
> 
> 已重置 2.1.3 2.2.0 报错均如上 可能是在这目录下迭代升级太多了 尝试换个目录新开poetry

2.0.1 以上就行，不行可能是你没装对位置，比如没有进虚拟环境
